# -*- coding: utf-8 -*-
"""final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181Lgtp4mW4dsGZU6g7VCDiV9MSc506rB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree

iris=load_iris()
x=iris.data
y=iris.target

df=pd.DataFrame(data=x,columns=iris.feature_names)
df['species']=pd.Categorical.from_codes(y,iris.target_names)

(df['species'])
(df.describe())
(df.shape)
(df.info())

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
(x_train)
(y_train)

md=DecisionTreeClassifier(random_state=42)
md.fit(x_train,y_train)

yprd=md.predict(x_test)

yprd=plt.figure(figsize=(20,10))
tree.plot_tree(md,filled=True,feature_names=iris.feature_names,class_names=iris.target_names)
plt.title('Decision Tree visualization')
plt.show()

ac=accuracy_score(y_test,yprd)
ac

